version: '3'
services:
  instapy:
    image: felixbreuer/instapy:latest
    container_name: instapy
    volumes:
      - instapy-data:/usr/instapy/InstaPy
    environment:
      - INFLUXDB_DB=instapy
      - INFLUXDB_USER=instapy
      - INFLUXDB_PASSWORD=instapysecret
      - INFLUXDB_HOST=influxdb
    depends_on:
      - mongo
    networks:
      - instapy-net
  webserver:
    image: felixbreuer/instapy-webserver:latest
    container_name: instapy-webserver
    restart: unless-stopped
    depends_on:
      - config
      - socket
      - influxdb
      - grafana
      - mongo
    ports:
      - 80:80
    networks:
      - instapy-net
  config:
    image: felixbreuer/instapy-config:latest
    container_name: instapy-config
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - instapy-data:/usr/instapy/assets
    networks:
      - instapy-net
  socket:
    image: felixbreuer/instapy-socket:latest
    container_name: instapy-socket
    restart: unless-stopped
    depends_on:
      - instapy
    environment:
      - FILESYSTEM=unix
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - instapy-net
  influxdb:
    image: influxdb:alpine
    container_name: instapy-influxdb
    restart: unless-stopped
    volumes:
      - instapy-influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=instapy
      - INFLUXDB_ADMIN_USER=instapy
      - INFLUXDB_ADMIN_PASSWORD=instapysecret
    networks:
      - instapy-net
  grafana:
    image: felixbreuer/instapy-grafana:latest
    container_name: instapy-grafana
    restart: unless-stopped
    depends_on:
      - influxdb
      - mongo
    volumes:
      - instapy-grafana:/var/lib/grafana
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=instapy
      - INFLUXDB_PASSWORD=instapysecret
      - INFLUXDB_DB=instapy
      - GF_SECURITY_ADMIN_USER=instapy
      - GF_SECURITY_ADMIN_PASSWORD=instapysecret
    networks:
      - instapy-net
  mongo:
    image: mongo:latest
    container_name: instapy-mongo
    restart: unless-stopped
    volumes:
      - instapy-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=instapy
      - MONGO_INITDB_ROOT_PASSWORD=instapysecret
    networks:
      - instapy-net

networks:
  instapy-net:
    driver: bridge

volumes:
  instapy-data:
  instapy-influxdb:
  instapy-grafana:
  instapy-mongo: